apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wedit-production-ingress
  namespace: wedit-production
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
spec:
  ingressClassName: nginx
  rules:
    - host: api.wedit.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wedit-production-service
                port:
                  number: 80