apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wedit-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/wedit-official/wedit-manifest.git
    targetRevision: HEAD
    path: argocd/envs
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
